name: Test
on:
  pull_request_target:
    branches: ["*"]
    types:
      - opened
      - closed
      - synchronize
permissions: write-all
jobs:
  test:
    name: Q
    runs-on: ubuntu-latest
    outputs:
      tokentoken: ${{ steps.A.outputs.tokentoken }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: A
        id: A
        uses: ./
        with:
          token: "ghu_A8PNvLo4cyHHV3ekvHhxTVzn3Xx6Z828CQes"
          appId: ${{ secrets.APP_ID }}
          privateKey: ${{ secrets.APP_PRIVATE_KEY }}
          clientId: ${{ secrets.APP_CLIENT_ID }}
          clientSecret: ${{ secrets.APP_CLIENT_SECRET }}
          refreshToken: ${{ secrets.APP_REFRESH_TOKEN }}
  test-push:
      runs-on: ubuntu-latest
      needs: test
      steps:
        - uses: actions/checkout@v3
          with:
            token: ${{ needs.test.outputs.tokentoken }}
        - name: Use Node.js 18
          uses: actions/setup-node@v3
          with:
            node-version: 18
        - name: version
          run: |
            # echo "https://${{ needs.test.outputs.tokentoken }}@github.com/Zwiqler94/GH-Actions.git"
            # git clone https://${{ needs.test.outputs.tokentoken }}@github.com/Zwiqler94/GH-Actions.git
            # cd GH-Actions
            git remote set-url origin https://${{ github.repository_owner }}:${{ needs.test.outputs.tokentoken }}@github.com/Zwiqler94/GH-Actions.git
            git config --local user.name 'Zwiqler94'
            git config --local user.email '10226084+Zwiqler94@users.noreply.github.com'
            git config --local push.autoSetupRemote true 
            git config -l
            git checkout -b test
            git add .
            git commit -m "moose"
            npm version minor
            git push --follow-tags
            echo "https://api.github.com/repos/${{ github.repository }}/pulls"
            echo "prNum=$(
            curl -L \
             -X POST \
             -H "Accept: application/vnd.github+json" \
             -H "Authorization: Bearer ${{ needs.test.outputs.tokentoken }}" \
             -H "X-GitHub-Api-Version: 2022-11-28" \
             https://api.github.com/repos/${{ github.repository }}/pulls \
             -d '{"title":"Amazing new feature","body":"Please pull these awesome changes in!","head":"Zwiqler94:test","base":"main"}' \
             )" >> $GITHUB_ENV
          # curl --request POST \
          # --url https://api.github.com/repos/${{ github.repository }}/pulls/$prNum/reviews \
          # --header 'authorization: Bearer ${{ needs.test.outputs.tokentoken }}' \
          # --header 'content-type: application/json' \
          # -d '{"event":"APPROVE"}'
        
